### ISSUE TITLE
Replace boxes in vignettes like distributions.Rmd that stopping equations rendering on website

### ISSUE THREAD

**Issue by joethorley** [poissonconsulting/ssdtools#105]
Replace with comment that was box previously in case want to try to implement in the future.

**Comment by joethorley** [comment]
This should be done by forking from the dev branch followed by a PR to the dev branch.

The dev website renders at

https://poissonconsulting.github.io/ssdtools/dev/

**Comment by dunkenwg** [comment]
Steps:
- [x] Fork dev branch
- [ ] Either quickly figure out how to fix the rendering of latex equations in boxes OR comment out boxes
- [ ] Pull request dev branch and check dev website before merging into main

https://poissonconsulting.github.io/ssdtools/dev/articles/distributions.html
<img width="613" alt="Screenshot 2024-11-07 at 11 20 32 AM" src="https://github.com/user-attachments/assets/e1403290-cb35-4e56-ae61-6a730d25181f">
